<!DOCTYPE html>
<html>
    <head>
        <title>CM OnBoarding Preview</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <link rel="stylesheet" href="<?php echo $cssPath; ?>" type="text/css"/>
        <?php
        $scripts = print_head_scripts();
        $styles = print_admin_styles();
        ?>
    </head>
    <body style="background-color: grey">
    </body>
</html>
